### ISSUE TITLE
How should the configuration look like?

### ISSUE THREAD

**Issue by TimPietrusky** [synoa/cerebro.pimcore.thumbnail#1]
I used https://github.com/synoa/cerebro.pimcore.thumbnail/releases/tag/1.1.1 and https://github.com/synoa/cerebro.pimcore.thumbnail/releases/tag/1.1.2 and the configuration as documented in the REAMDE doesn't work. I had to change it like this:

```
api_thumbnails:
    thumbnails:
        synoa_hd:
            asset_dir: "synoa_hd"
            generation_dir: "web/var/thumbnails"
```

Is that correct and we should update the README and every project that is using this?
